version: "2"
linters:
  enable:
    - promlinter
    - unconvert
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/onflow/flow-batch-scan
  exclusions:
    generated: lax
