name: Check License Header
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  check_licence_header:
    name: Check License Header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          config: .github/licenserc.yml